esp32:
  board: esp32-poe
  flash_size: 16MB
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

i2c:
  sda: 13
  scl: 16
  scan: true
  id: i2c_bus